export const hebrewReviewChanges = [
  {
    title: 'פנדה ענקית',
    description: 'מין של יונק ממשפחת הדוביים שמקורו בסין',
    editor: 'Alun Ap Owin',
    time: 'לפני דקה',
    oldRevisionId: 42469604,
    revisionId: 43654593,
    revisionDate: '25 ביולי 2026, 20:30',
    summary: 'עדכון מידע בסעיף הסיווג הטקסונומי',
    tags: ['עריכה חזותית'],
    wikiHost: 'he.wikipedia.org',
  },
  {
    title: 'אקסולוטל מקסיקני',
    description: 'דו־חי מימי שמקורו במקסיקו',
    editor: 'אלאורי',
    time: 'לפני 2 דקות',
    oldRevisionId: 42772895,
    revisionId: 43677868,
    revisionDate: '30 ביולי 2026, 10:37',
    summary: 'הגהת התיאור של האקסולוטל',
    tags: ['עריכה חזותית'],
    wikiHost: 'he.wikipedia.org',
  },
  {
    title: 'טיגריס',
    description: 'מין החתול הגדול ביותר החי כיום',
    editor: 'רוגד',
    time: 'לפני 3 דקות',
    oldRevisionId: 43172968,
    revisionId: 43257085,
    revisionDate: '15 במאי 2026, 15:29',
    summary: 'עריכת לשון קלה בתוכן הערך',
    tags: ['עריכה חזותית'],
    wikiHost: 'he.wikipedia.org',
  },
  {
    title: 'סחלביים',
    description: 'משפחה מגוונת של צמחים בעלי פרחים',
    editor: 'Hacodu',
    time: 'לפני 4 דקות',
    oldRevisionId: 40453059,
    revisionId: 40569335,
    revisionDate: '20 בפברואר 2025, 17:47',
    summary: 'שיפור קישורים פנימיים בתוכן הערך',
    tags: ['עריכה חזותית'],
    wikiHost: 'he.wikipedia.org',
  },
  {
    title: 'לווייתן כחול',
    description: 'יונק ימי והחיה הגדולה ביותר המוכרת',
    editor: 'Dannidissen',
    time: 'לפני 5 דקות',
    oldRevisionId: 41601808,
    revisionId: 42131844,
    revisionDate: '6 בנובמבר 2025, 20:29',
    summary: 'שיפור הניסוח בסעיף ההתנהגות, התזונה ומחזור החיים',
    tags: ['עריכה חזותית'],
    wikiHost: 'he.wikipedia.org',
  },
]
