export const thaiReviewChanges = [
  {
    title: 'แพนด้ายักษ์',
    description: 'สัตว์เลี้ยงลูกด้วยนมในวงศ์หมี มีถิ่นกำเนิดในประเทศจีน',
    editor: '110.78.147.4',
    time: '1 นาทีที่แล้ว',
    oldRevisionId: 12087272,
    revisionId: 12087278,
    revisionDate: '13 มกราคม 2568, 08:47',
    summary: 'ปรับปรุงข้อความเกี่ยวกับลักษณะของแพนด้ายักษ์',
    tags: ['แก้ไขด้วยตัวแก้ไขแบบเห็นภาพ'],
    wikiHost: 'th.wikipedia.org',
  },
  {
    title: 'แอกโซลอเติล',
    description: 'สัตว์สะเทินน้ำสะเทินบกที่อาศัยอยู่ในน้ำจากประเทศเม็กซิโก',
    editor: '- ikkue -',
    time: '2 นาทีที่แล้ว',
    oldRevisionId: 12594976,
    revisionId: 12594978,
    revisionDate: '12 ตุลาคม 2568, 09:15',
    summary: 'แก้ไขข้อความและชื่อลิงก์',
    tags: ['แก้ไขด้วยตัวแก้ไขแบบเห็นภาพ'],
    wikiHost: 'th.wikipedia.org',
  },
  {
    title: 'เสือ',
    description: 'สัตว์ในวงศ์แมวขนาดใหญ่ที่สุดที่ยังมีชีวิตอยู่',
    editor: 'XbruhingX',
    time: '3 นาทีที่แล้ว',
    oldRevisionId: 12848085,
    revisionId: 12979979,
    revisionDate: '2 พฤษภาคม 2569, 11:38',
    summary: 'เพิ่มรายละเอียดเกี่ยวกับลักษณะและถิ่นอาศัยของเสือ',
    tags: ['แก้ไขด้วยตัวแก้ไขแบบเห็นภาพ'],
    wikiHost: 'th.wikipedia.org',
  },
  {
    title: 'กล้วยไม้',
    description: 'วงศ์พืชดอกที่มีความหลากหลายสูง',
    editor: 'Waniosa Amedestir',
    time: '4 นาทีที่แล้ว',
    oldRevisionId: 11506875,
    revisionId: 11669081,
    revisionDate: '15 พฤษภาคม 2567, 16:42',
    summary: 'ปรับปรุงคำอธิบายเกี่ยวกับกล้วยไม้',
    tags: ['แก้ไขด้วยตัวแก้ไขแบบเห็นภาพ'],
    wikiHost: 'th.wikipedia.org',
  },
  {
    title: 'วาฬสีน้ำเงิน',
    description: 'สัตว์เลี้ยงลูกด้วยนมในทะเลและสัตว์ที่มีขนาดใหญ่ที่สุด',
    editor: '27.130.125.138',
    time: '5 นาทีที่แล้ว',
    oldRevisionId: 10949740,
    revisionId: 10949780,
    revisionDate: '17 สิงหาคม 2566, 04:14',
    summary: 'ปรับปรุงข้อมูลเกี่ยวกับความยาวของวาฬสีน้ำเงิน',
    tags: ['แก้ไขต้นฉบับ'],
    wikiHost: 'th.wikipedia.org',
  },
]
